name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@2.0.0
  with:
    # FTP server name (you may need to specify a port)
    ftp_server: files.000webhost.com
    # FTP account username
    ftp_username: sound-land
    # FTP account password
    ftp_password: 4m!iBQy@LX%8Xw4GBR*f
    # Protocol used to deploy (ftp or sftp)
    method: # optional, default is ftp
    # The port used to connect to server
    port: # optional, default is 21
    # The local folder to copy, defaults to root project folder
    local_dir: # optional, default is 
    # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
    remote_dir: /public_html/
    # Passes through options into lftp
    ARGS: --verbose --delete --exclude=/app/config/db.php --exclude=/app/config/db.version.json 
