on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: files.000webhost.com
        FTP_USERNAME: sound-land
        FTP_PASSWORD: 4m!iBQy@LX%8Xw4GBR*f
        REMOTE_DIR: /public_html/
        ARGS: --verbose --delete --exclude=/app/config/db.php --exclude=/app/config/db.version.json --exclude=/.git
